#!/usr/bin/env bash
#
# setup.sh — one-command organisation setup for Shenasa + Kanidm.
#
#   bash deploy/setup.sh idm.example.com                    # single-origin
#   bash deploy/setup.sh idm.example.com shenasa.example.com # two-domain
#   bash deploy/setup.sh idm.example.com --seed             # + operator provisioning
#
# What it does:
#   1. prepares deploy/{out,tls,ui}
#   2. generates a local CA + server certificate if none is configured
#      (replace tls/chain.pem + tls/key.pem with publicly-trusted material
#      for production)
#   3. renders out/server.toml and out/Caddyfile from the real domain(s)
#   4. copies the static SPA into deploy/ui (and points its default config
#      at the rendered domains)
#   5. starts Kanidm + Caddy with docker compose
#   6. runs bootstrap.sh (recover idm_admin, create the OAuth2 client)
#   7. optionally runs seed.sh
#
set -euo pipefail

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
REPO_ROOT=$(CDPATH= cd -- "$SCRIPT_DIR/.." && pwd)

log() { printf '[setup] %s\n' "$*"; }
die() { printf '[setup] ERROR: %s\n' "$*" >&2; exit 1; }
need() { command -v "$1" >/dev/null 2>&1 || die "missing dependency: $1"; }

DOMAIN=""
UI_DOMAIN=""
DO_SEED=0
for arg in "$@"; do
  case "$arg" in
    --seed) DO_SEED=1 ;;
    -h|--help)
      sed -n '2,22p' "$0"; exit 0 ;;
    *)
      if [ -z "$DOMAIN" ]; then DOMAIN=$arg;
      elif [ -z "$UI_DOMAIN" ]; then UI_DOMAIN=$arg;
      else die "unexpected argument: $arg"; fi ;;
  esac
done
[ -n "$DOMAIN" ] || die "usage: setup.sh <idm-domain> [ui-domain] [--seed]"
[ -z "$UI_DOMAIN" ] && UI_DOMAIN=$DOMAIN
TWO_DOMAIN=0
[ "$UI_DOMAIN" != "$DOMAIN" ] && TWO_DOMAIN=1

# Validate domains BEFORE they are interpolated into sed substitutions and
# the rendered Caddyfile/server.toml: an unvalidated value could inject
# configuration lines (or break the sed delimiters) into the generated
# configs. Hostname labels only: letters/digits/hyphen, dot-separated.
validate_domain() {
  [[ "$1" =~ ^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?(\.[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?)+$ ]] \
    && [[ ${#1} -le 253 ]] \
    || die "invalid domain name: '$1'"
}
validate_domain "$DOMAIN"
[ "$TWO_DOMAIN" = "1" ] && validate_domain "$UI_DOMAIN"

need docker
need openssl
need sed

mkdir -p "$SCRIPT_DIR/out" "$SCRIPT_DIR/tls" "$SCRIPT_DIR/ui"

# --- TLS material ------------------------------------------------------------
if [ ! -f "$SCRIPT_DIR/tls/chain.pem" ]; then
  log "generating a local CA and server certificate for $DOMAIN (dev/quickstart)…"
  openssl req -x509 -newkey rsa:4096 -sha256 -days 3650 -nodes \
    -subj "/CN=Shenasa quickstart CA" \
    -keyout "$SCRIPT_DIR/tls/ca-key.pem" -out "$SCRIPT_DIR/tls/ca.pem" >/dev/null 2>&1
  SAN="DNS:$DOMAIN"
  [ "$TWO_DOMAIN" = "1" ] && SAN="$SAN,DNS:$UI_DOMAIN"
  openssl req -newkey rsa:4096 -nodes \
    -subj "/CN=$DOMAIN" -addext "subjectAltName=$SAN" \
    -keyout "$SCRIPT_DIR/tls/key.pem" -out "$SCRIPT_DIR/tls/server.csr" >/dev/null 2>&1
  printf 'subjectAltName=%s\nbasicConstraints=CA:FALSE\nkeyUsage=digitalSignature,keyEncipherment\nextendedKeyUsage=serverAuth\n' "$SAN" \
    > "$SCRIPT_DIR/tls/server.ext"
  openssl x509 -req -sha256 -days 825 \
    -in "$SCRIPT_DIR/tls/server.csr" \
    -CA "$SCRIPT_DIR/tls/ca.pem" -CAkey "$SCRIPT_DIR/tls/ca-key.pem" -CAcreateserial \
    -extfile "$SCRIPT_DIR/tls/server.ext" \
    -out "$SCRIPT_DIR/tls/server.pem" >/dev/null 2>&1
  cat "$SCRIPT_DIR/tls/server.pem" "$SCRIPT_DIR/tls/ca.pem" > "$SCRIPT_DIR/tls/chain.pem"
  rm -f "$SCRIPT_DIR/tls/server.csr" "$SCRIPT_DIR/tls/server.ext" "$SCRIPT_DIR/tls/ca.srl"
  chmod 600 "$SCRIPT_DIR/tls/key.pem" "$SCRIPT_DIR/tls/ca-key.pem"
  chmod 644 "$SCRIPT_DIR/tls/ca.pem" "$SCRIPT_DIR/tls/chain.pem"
  log "dev CA written to tls/ca.pem — import it into browsers or replace tls/chain.pem+key.pem with real certificates."
else
  log "using existing tls/chain.pem + tls/key.pem (production certificates)."
fi

# --- Render configs -----------------------------------------------------------
log "rendering out/server.toml for domain $DOMAIN…"
sed "s/SHENASA_DOMAIN/$DOMAIN/g" "$SCRIPT_DIR/server.toml.example" > "$SCRIPT_DIR/out/server.toml"

# Reverification between re-runs: include the private-CA trust line only when
# a local CA actually exists (quickstart mode). With publicly-trusted
# certificates Caddy uses the system CA pool.
TRUST_CA_LINE=""
if [ -f "$SCRIPT_DIR/tls/ca.pem" ]; then
  TRUST_CA_LINE=$'\n\t\t\t\ttls_trusted_ca_certs /srv/tls/ca.pem'
fi

write_caddyfile() {
  local file="$SCRIPT_DIR/out/Caddyfile"
  cat > "$file" <<EOF
# Generated by deploy/setup.sh — edit deploy/Caddyfile.example instead.
{
	email admin@$DOMAIN
}

(security_headers) {
	header {
		Strict-Transport-Security "max-age=63072000; includeSubDomains; preload"
		X-Content-Type-Options "nosniff"
		X-Frame-Options "DENY"
		Referrer-Policy "no-referrer"
		Permissions-Policy "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()"
		-Server
	}
}

(spa_csp) {
	header Content-Security-Policy "default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' data:; connect-src 'self' https:; object-src 'none'; frame-ancestors 'none'; base-uri 'self'; form-action 'self'"
}
EOF
  if [ "$TWO_DOMAIN" = "0" ]; then
    cat >> "$file" <<EOF

# Topology A: single-origin — SPA under /admin/, everything else Kanidm.
https://$DOMAIN {
	import security_headers

	# The SPA uses relative asset paths, so it only works with the trailing
	# slash. Without this redirect, "/admin" renders a blank page (assets
	# resolve to /js/... and 404 on the Kanidm proxy). redir sorts before
	# handle in Caddy's default directive order.
	redir /admin /admin/ 308

	@admin path /admin/*
	handle @admin {
		import spa_csp
		uri strip_prefix /admin
		root * /srv/shenasa
		try_files {path} /index.html
		file_server
	}

	handle {
		reverse_proxy kanidm:8443 {
			transport http {
				tls
				tls_server_name $DOMAIN$TRUST_CA_LINE
			}
		}
	}

	# Remove this line to let Caddy obtain ACME certificates instead.
	tls /srv/tls/chain.pem /srv/tls/key.pem
}
EOF
  else
    cat >> "$file" <<EOF

# Topology B: two-domain — Kanidm on $DOMAIN, SPA on $UI_DOMAIN.
https://$DOMAIN {
	import security_headers
	handle {
		reverse_proxy kanidm:8443 {
			transport http {
				tls
				tls_server_name $DOMAIN$TRUST_CA_LINE
			}
		}
	}
	tls /srv/tls/chain.pem /srv/tls/key.pem
}

https://$UI_DOMAIN {
	import security_headers
	import spa_csp

	# Same-origin API proxy — the browser never needs CORS.
	@api path /v1/* /oauth2/* /_session/* /.well-known/*
	handle @api {
		reverse_proxy kanidm:8443 {
			transport http {
				tls
				tls_server_name $DOMAIN$TRUST_CA_LINE
			}
		}
	}

	handle {
		root * /srv/shenasa
		try_files {path} /index.html
		file_server
	}
	tls /srv/tls/chain.pem /srv/tls/key.pem
}
EOF
  fi
  log "rendered out/Caddyfile."
}
write_caddyfile

# --- Stage the SPA -------------------------------------------------------------
log "staging the SPA into deploy/ui…"
cp "$REPO_ROOT/index.html" "$SCRIPT_DIR/ui/index.html"
rm -rf "$SCRIPT_DIR/ui/css" "$SCRIPT_DIR/ui/js"
cp -r "$REPO_ROOT/css" "$SCRIPT_DIR/ui/css"
cp -r "$REPO_ROOT/js" "$SCRIPT_DIR/ui/js"

# Point the staged config at the rendered domains (still overridable at
# runtime with ?apiUrl=… and via the Settings page).
if [ "$TWO_DOMAIN" = "0" ]; then
  CFG_API="https://$DOMAIN/v1"
  CFG_REDIRECT="https://$DOMAIN/admin/"
else
  CFG_API="https://$UI_DOMAIN/v1"
  CFG_REDIRECT="https://$UI_DOMAIN/"
fi
sed -i.bak \
  -e "s#apiUrl: 'https://idm.example.com/v1'#apiUrl: '$CFG_API'#" \
  -e "s#oidcRedirectUri: 'https://idm.example.com/oauth2/redirect'#oidcRedirectUri: '$CFG_REDIRECT'#" \
  "$SCRIPT_DIR/ui/js/config.js"
rm -f "$SCRIPT_DIR/ui/js/config.js.bak"

# --- Start ---------------------------------------------------------------------
log "starting Kanidm + Caddy…"
if command -v docker >/dev/null 2>&1 && docker compose version >/dev/null 2>&1; then
  COMPOSE=(docker compose -f "$SCRIPT_DIR/docker-compose.yml")
else
  COMPOSE=(docker-compose -f "$SCRIPT_DIR/docker-compose.yml")
fi
WAS_RUNNING=$("${COMPOSE[@]}" ps -q 2>/dev/null | wc -l)

# --- Downgrade guard -----------------------------------------------------------
# Kanidm migrations are ONE-WAY: a database migrated by version N is refused
# by every older server (MG0010DowngradeNotAllowed) which then crash-loops and
# leaves the readiness wait below hanging. A re-unzipped release zip silently
# resets the pinned image to the release default, which may be older than the
# tag this host already runs — refuse BEFORE recreating any container.
PINNED_TAG=$(sed -n 's/^[[:space:]]*image:[[:space:]]*kanidm\/server://p' \
  "$SCRIPT_DIR/docker-compose.yml" | head -n1 | tr -d "\"'[:space:]")
DEPLOYED_TAG=$(docker inspect -f '{{.Config.Image}}' shenasa-kanidm 2>/dev/null \
  | sed -n 's#.*kanidm/server:##p' | head -n1 || true)
if [ -n "$PINNED_TAG" ] && [ -n "$DEPLOYED_TAG" ] && [ "$PINNED_TAG" != "$DEPLOYED_TAG" ]; then
  case "$PINNED_TAG.$DEPLOYED_TAG" in
    *[!0-9.]*)
      log "WARNING: non-semver image tag (pinned='$PINNED_TAG' deployed='$DEPLOYED_TAG') — cannot verify downgrade safety." ;;
    *)
      if [ "$PINNED_TAG" = "$(printf '%s\n%s\n' "$PINNED_TAG" "$DEPLOYED_TAG" | sort -V | head -n1)" ]; then
        printf '[setup] ERROR: refusing to DOWNGRADE Kanidm: deployed %s > pinned %s.\n' "$DEPLOYED_TAG" "$PINNED_TAG" >&2
        printf '        This host already ran kanidm/server:%s; its database migration is ONE-WAY and an\n' "$DEPLOYED_TAG" >&2
        printf '        older server would fail with MG0010DowngradeNotAllowed.\n' >&2
        printf '        Fix: re-pin deploy/docker-compose.yml to kanidm/server:%s, then re-run setup.sh.\n' "$DEPLOYED_TAG" >&2
        printf '        Policy: https://kanidm.github.io/kanidm/stable/support.html#upgrade-policy\n' >&2
        exit 1
      fi
      log "NOTICE: pinned $PINNED_TAG > deployed $DEPLOYED_TAG — this run will UPGRADE Kanidm (one-way DB migration)."
      log "        Ctrl+C within 5s to abort and back up first (see deploy/README.md)…"
      sleep 5 ;;
  esac
fi

"${COMPOSE[@]}" up -d
# Re-running setup must pick up re-rendered Caddyfile/server.toml (bind mounts).
if [ "$WAS_RUNNING" -gt 0 ]; then
  "${COMPOSE[@]}" restart
fi

# Wait against the DOMAIN (the certificate name), resolved to localhost, so
# certificate verification matches in every mode. Local CA is only trusted
# when it exists (quickstart); public certs use the system CA pool.
CURL_CA=()
[ -f "$SCRIPT_DIR/tls/ca.pem" ] && CURL_CA=(--cacert "$SCRIPT_DIR/tls/ca.pem")
log "waiting for Kanidm to answer TLS as $DOMAIN:8443…"
TRIES=0
until curl -fsS "${CURL_CA[@]}" --resolve "$DOMAIN:8443:127.0.0.1" -o /dev/null "https://$DOMAIN:8443/" 2>/dev/null || [ $TRIES -ge 60 ]; do
  TRIES=$((TRIES + 1))
  sleep 2
done
if [ $TRIES -ge 60 ]; then
  if "${COMPOSE[@]}" logs --tail=300 kanidm 2>/dev/null | grep -q 'MG0010DowngradeNotAllowed'; then
    printf '[setup] ERROR: Kanidm refused to start: MG0010DowngradeNotAllowed (one-way migration).\n' >&2
    printf '        The database was already migrated by a NEWER Kanidm than the pinned image (%s).\n' "$PINNED_TAG" >&2
    printf '        A re-unzip may have reset deploy/docker-compose.yml to an older default pin.\n' >&2
    printf '        Fix: re-pin deploy/docker-compose.yml to the newer tag your deployment last ran, then:\n' >&2
    printf '          %s up -d\n' "${COMPOSE[*]}" >&2
    printf '        Policy: https://kanidm.github.io/kanidm/stable/support.html#upgrade-policy\n' >&2
    exit 1
  fi
  die "Kanidm did not become ready in 120s — check: ${COMPOSE[*]} logs kanidm caddy"
fi
log "Kanidm is ready."

# --- Bootstrap -------------------------------------------------------------------
if [ "$TWO_DOMAIN" = "0" ]; then
  BOOT_REDIRECT="https://$DOMAIN/admin/"
else
  BOOT_REDIRECT="https://$UI_DOMAIN/"
fi
KANIDM_DOMAIN=$DOMAIN \
KANIDM_API_ORIGIN="https://$DOMAIN:8443" \
KANIDM_TLS_CA="$SCRIPT_DIR/tls/ca.pem" \
SHENASA_REDIRECT_URI="$BOOT_REDIRECT" \
  bash "$SCRIPT_DIR/bootstrap.sh"

if [ "$DO_SEED" = "1" ]; then
  log "running optional provisioning (seed.sh)…"
  KANIDM_DOMAIN=$DOMAIN KANIDM_TLS_CA="$SCRIPT_DIR/tls/ca.pem" bash "$SCRIPT_DIR/seed.sh"
fi

cat <<EOF

============================================================
 Deployment complete
============================================================
 Kanidm:      https://$DOMAIN
 Shenasa UI:  $( [ "$TWO_DOMAIN" = "0" ] && echo "https://$DOMAIN/admin/" || echo "https://$UI_DOMAIN/" )
 API (v1):    $( [ "$TWO_DOMAIN" = "0" ] && echo "https://$DOMAIN/v1" || echo "https://$UI_DOMAIN/v1" )

 Sign in with "Sign in with SSO" after adding users to the role groups
 (e.g. idm_people_admins) — see deploy/README.md for the verification
 checklist and the GO-LIVE-checklist.md for publishing.
============================================================
EOF
